name: Build Release Binaries

on:
  release:
    types: [published]

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    permissions:
      contents: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Linux binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o myapp-linux-amd64 ./main.go

      - name: Build Windows binary
        run: |
          GOOS=windows GOARCH=amd64 go build -o myapp-windows-amd64.exe ./main.go

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            myapp-linux-amd64
            myapp-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
