name: Go Release Build

on:
  release:
    types: [published]

jobs:
  build:
    name: Build for Windows and Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest main branch
        uses: actions/checkout@v1
        with:
          ref: main 

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.24'

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o build/myapp-linux main.go

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o build/myapp-windows.exe main.go

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: go-binaries
          path: build/
